### ISSUE TITLE
Adjusting input size when using Bootstrap & a string mask

### ISSUE THREAD

**Issue by OctoCoder207** [DesertFoxNV/ngx-autosize-input#24]
Hi. I noticed that adjusting the input size does not work in this case.

[https://stackblitz.com/edit/ngx-autosize-input-z1jmwu?devtoolsheight=33&file=src/app/app.component.ts](url)

Thanks for looking into it! 👍

**Comment by joshuawwright** [comment]
@OctoCoder207

The problem is a css issue. In your example above you are setting the parent width. If you want your input to size to the parent width you will need to adjust the width of your input to automatically scale to the parent.

![image](https://user-images.githubusercontent.com/1731346/98380305-a0d26380-2005-11eb-8a9a-600f18915fe6.png)

Another way to visually see the issue is to add `style="overflow: hidden"` to the parent div. You will then see that the input is cut off because the input is not scaling to the parent div. 

![image](https://user-images.githubusercontent.com/1731346/98380689-20603280-2006-11eb-9ead-402e3beaf966.png)

To make the input scale with the parent div I added the `style="width: 100%"` to the input.  Now you can see the input scales to the placeholder, since the value is undefined:

![image](https://user-images.githubusercontent.com/1731346/98381261-e3e10680-2006-11eb-87b4-de85194f6dbd.png)

If you want the text mask to be shown, then you will want to change the placeholder text to `___-____.__`. This will result in the following:
![image](https://user-images.githubusercontent.com/1731346/98381568-4a662480-2007-11eb-98ce-67e309f56019.png)

I hope that helps!

**Comment by joshuawwright** [comment]
I assume that this has been solved, if not we can re-open this issue.
